package objects

const TemplateStart string = "<html><head><title>Начальные параметры</title></head><body><form action=\"http://127.0.0.1/game?key=start\" method=\"post\"><h2>Выбери уровень сложности:</h2><select name=\"difficulty\"><option value=\"Easy\" selected>Легкий</option><option value=\"Normal\">Нормальный</option><option value =\"Hard\">Тяжелый</option></select><h2>Придумай имя своему персонажу:</h2><input type=\"text\" name=\"gamer\" value=\"Ленивая жопа\" size=\"15\"><br><br><input type=\"submit\" value=\"Начать игру!\"></form></body></html>"
const TemplateHello string = "<html><head><title>Приветствие!</title></head><body><form action=\"http://127.0.0.1/game?key=action\" method=\"post\"><h2>Привет, {{ .Name}}!</h2>Ты попал в жестокий мир, в котором тебе придется выживать.<br>Опасность тут на каждом шагу - дикие животные и другие выжившие!<br>Иди вперед и не оглядывайся! Сможешь выбраться отсюда?<br><br><input type=\"submit\" value=\"Я готов!\"></form></body></html>"
const TemplateSelectWay string = "<html><head><title>Выбор пути</title></head><body><form action=\"http://127.0.0.1/game?key=event\" method=\"post\">Ты решил идти дальше! Что ждет тебя впереди?<br>Посмотрев по сторонам ты видишь:<br><br>{{ .One}} - {{ .OneText}}<br>{{ .Two}} - {{ .TwoText}}<br>{{ .Three}} - {{ .ThreeText}}<h2>Выбери куда пойдешь дальше:</h2><select name=\"select\"><option value= {{ .One}}>{{ .One}}</option><option value={{ .Two}}>{{ .Two}}</option><option value ={{ .Three}}>{{ .Three}}</option></select><br><br><input type=\"submit\" value=\"Идти!\"></form></body></html>"
const TemplateSelectAction string = "<html><head><title>Выбор действия</title></head><body><form action=\"http://127.0.0.1/game?key=actionDone\" method=\"post\">{{ .TextAll}}<h2>Что будешь делать дальше?</h2><select name=\"action\"><option value=find>Обследовать</option><option value=selectWay>Идти дальше</option><option value =sleep>Отдохнуть</option><option value =bonfire>Развести костер</option><option value =backpack>Заглянуть в рюкзак</option><option value =craft>Создать предмет</option><option value =apply>Применить предмет</option></select><br><br><input type=\"submit\" value=\"Действуй!\"></form></body></html>"
const TemplateAttackOnGamer string = "<html><head><title>Атака</title></head><body><form action=\"http://127.0.0.1/game?key=action\" method=\"post\">{{ .TextAll}}<h3>Что будешь делать?</h3><select name=\"battle\"><option value=leave>Убежать</option><option value=figth>Драться</option></select><br><br><input type=\"submit\" value=\"Действуй!\"></form></body></html>"
const TemplateGamerAttack string = "<html><head><title>Находка</title></head><body><form action=\"http://127.0.0.1/game?key=action\" method=\"post\">{{ .TextAll}}<h3>Что будешь делать?</h3><select name=\"gamerBattle\"><option value=leave>Уйти</option><option value=figth>Атаковать</option></select><br><br><input type=\"submit\" value=\"Действуй!\"></form></body></html>"

var TemplateCraft string    // Динамический шаблон для крафта
var TemplateEndGame string  // Динамический шаблон окончания игры
var TemplateApply string    //  Динамический шаблон для применения предметов
var TemplateBackpack string // Динамический шаблон для просмотра рюкзака
